### PR TITLE
Add support for signals

### PR DESCRIPTION
**Pull request by Djedouas**
All pyqt signals are now typed as such

### CODE REVIEW

**Comment by Djedouas** [comment]
I ran into a problem when connecting QMenu().aboutToShow() signal :
`projectMenu.aboutToShow.connect(self.controller.saveSettings)`

Which creates a mypy error:
` news_view.py:93:9: error: "Callable[[], None]" has no attribute "connect"`

So I decided to patch all others signals in `QtWidgets.pyi`, like it was already done for `QAbstractButton`

**Comment by The-Compiler** [comment]
Did you automate this in some way? Why only `QtWidgets.pyi`?

**Comment by Djedouas** [comment]
It's handmade. That's why it's only `QtWidgets.pyi`.
Therefore it can not be considered completely exhaustive, like before.

**Comment by stlehmann** [comment]
Thanks for your effort of manually adding the signals. I know that's a tedious work. I would like to have a way to automate this stuff. Thanks again :)

**Comment by Djedouas** [comment]
Thanks a lot!
Happy to participate ;-)

**Pull request merged**
