### PR TITLE
Some signals for QtCore, QtWidgets, QTNetworking added QtSerialPort newly created

### PR DESCRIPTION
**Pull request by Schleehauf**
In the original version the signals were contained as methods.

### CODE REVIEW

**Comment by stlehmann** [comment]
Your PR seems to be broken. Please make sure the diff contains only the lines that you changed. Otherwise it is impossible for me to tell which lines you changed. Also please make sure that the checks are passed. Thx.

**Comment by Schleehauf** [comment]
Please carefully review the new QtSerialPort.pyi, I am not sure if I fully understood how to put in Enums and flags.

**Review by stlehmann — APPROVED** [review]

**Comment by stlehmann** [comment]
Please do not delete the original lines. Instead comment them out and add a note which issue you addressed by changing them.

**Review by stlehmann — CHANGES_REQUESTED** [review]
Please comment out the original code lines instead of deleting them. Also add a comment which issue (see issues.md) you are addressing. Have a look at the recent code changes for an example.

**Pull request closed without merging**
