### PR TITLE
Build 5.15.4

### PR DESCRIPTION
**Pull request by altendky**
Draft for:
- [x] Some confidence this is right...

### CODE REVIEW

**Comment by altendky** [comment]
@BryceBeagle, should we still be building the stubs as opposed to getting them from the wheels?  I never feel like I know if I am getting the right versions of each thing from each place, etc.

**Comment by altendky** [comment]
@BryceBeagle, should we still be building the stubs as opposed to getting them from the wheels?  I never feel like I know if I am getting the right versions of each thing from each place, etc.

**Comment by BryceBeagle** [comment]
iirc, we've been building the stubs since before the wheels shipped with them. They may be equivalent at this point. However, as [not all of the bindings are available on PyPI](https://github.com/python-qt-tools/PyQt5-stubs/pull/138#issuecomment-789593180), we'd need to either drop support or continue building some of them.

**Comment by altendky** [comment]
The changelog in the sdist doesn't show anything significant so maybe this is really all there is to be changed.

```
2021-03-05  Phil Thompson  <phil@riverbankcomputing.com>

	* NEWS:
	Released as v5.15.4.
	[b30547186181] [5.15.4] <5.15-maint>

	* qpy/QtCore/qpycore_qt_conf.cpp:
	Fixed the embedded conf file.
	[28d8448d1ec4] <5.15-maint>

2021-03-04  Phil Thompson  <phil@riverbankcomputing.com>

	* lib/configure.py, lib/project.py:
	Fixed the Qt subdirectory in __init__.py.
	[1cd001d504ab] <5.15-maint>

2021-03-02  Phil Thompson  <phil@riverbankcomputing.com>

	* NEWS:
	Updated the NEWS file.
	[755c706e32ba] <5.15-maint>

2021-02-27  Phil Thompson  <phil@riverbankcomputing.com>

	* lib/pyproject.toml:
	Fixed the project dependencies.
	[f945ce38080e] <5.15-maint>

	* rb-product, rb-product.toml:
	Updated the product file.
	[fc2239114623] <5.15-maint>
```

**Review by BryceBeagle — APPROVED** [review]
Easy enough. Shall we also bump the Arch Linux Docker Image (and remove our workaround)? I believe the glibc issue has been resolved by now.

Or would you rather that in another PR?

**Comment by altendky** [comment]
Separate I guess...

**Pull request merged**
