### PR TITLE
Fix annotations for QTableWidget #151

### PR DESCRIPTION
**Pull request by TilmanK**
Ok, so here's the PR. I've tested every method and indeed every one of them either returns a `None` when called with invalid values or accepts `None` as argument, which is convenient regarding use-cases like this:

```py
row = table_widget.row(table_widget.itemAt(QPoint(42, 42)))
```

I'll update the PR later today with fixes for `QListWidget` and `QTreeWidget` as well.

### CODE REVIEW

**Comment by TilmanK** [comment]
@bluebird75 Go ahead, it's complete. I've confirmed in simple examples that the changes are correct - you can really build complex widget structures just by passing None around ;)

**Review by bluebird75 — APPROVED** [review]

**Comment by bluebird75** [comment]
Nice.

Unrelated but I want to get started on PyQt6-stubs. Can you rejoin the thread on #69 ? I see that you have a repo with some code for it.

**Comment by mkrieger1** [comment]
I believe `QTableWidget.cellWidget` should return `Optional[QWidget]`, not `List[QWidget]`. Can someone confirm that `List[QWidget]` was a mistake, or am I wrong?

(I already wrote an inline comment [here](https://github.com/python-qt-tools/PyQt5-stubs/commit/cd0c74401d9d4fb50761b9849e7a229d6470c4d7), but I'm not sure if this triggered a notification for anybody involved.)

**Comment by altendky** [comment]
https://doc.qt.io/qt-5/qtablewidget.html#cellWidget
> `[QWidget](https://doc.qt.io/qt-5/qwidget.html#QWidget) *QTableWidget::cellWidget(int row, int column) const`

Looks like it shouldn't be a `List`, yeah.  It doesn't clearly state that the pointer can be `NULL`, but I'd guess it can be.  Maybe you could explore at runtime to double check?  And provide a pr?

**Comment by mkrieger1** [comment]
Created #198.

**Pull request merged**
