### PR TITLE
Gui-less application

### PR DESCRIPTION
**Pull request by bluebird75**
Example of creating a QApplication() and a QWidget() in an gui-less environment.

Fixes #165  and #166

### CODE REVIEW

**Comment by TilmanK** [comment]
Go ahead and merge.

**Comment by bluebird75** [comment]
I can not merge without an external review. If you have review power, please use it :-)

**Comment by TilmanK** [comment]
I don't. But @altendky has and will surely do us the favor ;)

**Comment by bluebird75** [comment]
#166 is taking care of this. So closing current PR.

**Pull request closed without merging**
