### PR TITLE
Release v5.15.2.0

### LINKED ISSUE #115: Make a release?  (after 5.15.2?)
It seems like it might be a reasonable idea to make a release.  There are plenty of bits to still work on but there have been a lot of changes.  Maybe after #113 makes it across with 5.15.2?  I'm not presently doing anything where I need this but if nothing else it gives us a chance to figure out how releases have been happening.  Any thoughts @stlehmann?

### PR DESCRIPTION
**Pull request by altendky**
Closes #115.

### CODE REVIEW

**Comment by altendky** [comment]
I guess I may as well provide the to-be-uploaded files here.  These were built from 2aa40a95fd060a7407baa58ed3af9125d81ca1ca.  If approved, that will be the commit to get tagged as `5.15.2.0`.

(thanks GitHub for making me pretend these are `.txt` files...)
[PyQt5_stubs-5.15.2.0-py3-none-any.whl.txt](https://github.com/python-qt-tools/PyQt5-stubs/files/6018271/PyQt5_stubs-5.15.2.0-py3-none-any.whl.txt)
[PyQt5-stubs-5.15.2.0.tar.gz.txt](https://github.com/python-qt-tools/PyQt5-stubs/files/6018272/PyQt5-stubs-5.15.2.0.tar.gz.txt)

**Comment by BryceBeagle** [comment]
To confirm, this would get merged into master, we'd tag the commit, and CI will be expected to build/deploy the wheels?

**Comment by altendky** [comment]
Yes, no, and no.  As per the present plan.  It would get merged into master after adding the guessed next release number to the changelog (or could be just `[unreleased]` leaving the version number un-guessed).  The tag would be applied to the commit on the branch mentioned above (2aa40a95fd060a7407baa58ed3af9125d81ca1ca).  At present, CI doesn't even archive a wheel and sdist, let alone publish it.

https://github.com/python-qt-tools/PyQt5-stubs/issues/115#issuecomment-779538224

More automation would be nice and might follow at some point, but I don't think we ought to wait for it to release.

**Comment by BryceBeagle** [comment]
So then where did the files you attached come from? Did you manually make them? Will you be manually pushing them to PyPI?

**Comment by altendky** [comment]
A local copy of the repo at the linked commit with a run of `git clean -ffdx` then env creation and `python -m build --sdist --wheel` to build them.  Yes manual creation and pushing is proposed for now.

**Review by BryceBeagle — APPROVED** [review]

**Comment by altendky** [comment]
https://pypi.org/project/PyQt5-stubs/5.15.2.0/

**Comment by The-Compiler** [comment]
Yay! :tada:

It looks like you didn't create a release on GitHub, so I [took the freedom](https://github.com/python-qt-tools/PyQt5-stubs/releases/tag/5.15.2.0) to do so.

**Comment by altendky** [comment]
Yeah, that's on the list of things I haven't gotten myself familiar with.  I think I've seen pushing a tag create a draft release?  Then you can go and copy the changelog in as a message and make a final release?  Looks like it could afford to have the sdist and wheel added?

**Pull request merged**
