### PR TITLE
Remove PyQt5.sip.array from allowlist

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by altendky** [comment]
Given the failure on `master`, presumably this will break 3.6 though I haven't identified why quite yet.

**Comment by altendky** [comment]
https://www.diffchecker.com/QDxLmKiR shows `PyQt5-sip==12.9.1` vs. `PyQt5-sip==12.11.0` so I guess that's the issue.

**Comment by altendky** [comment]
I don't necessarily like this, but it's an option and confirms the problem.

**Review by bluebird75 — APPROVED** [review]
Approved. I am just concerned generally of how many specific allowlist we have to manage

**Comment by bluebird75** [comment]
The unbreakage seems to come from PyQt5-sip moving from 12.10.1 to 12.11.0 for python > 3.6 .

**Pull request merged**
