### PR TITLE
Build 5.15.0

### PR DESCRIPTION
**Pull request by altendky**
Draft for:
- [x] Rebuilding SIP stubs
- [x] Unbreak CI back to its regular brokenness
   - Nevermind, in this case upstream 5.15.0 really just is that broken.

### CODE REVIEW

**Comment by altendky** [comment]
Am I supposed to rebuild the `PyQt5-Stubs/sip.pyi` somehow?

**Comment by BryceBeagle** [comment]
I think building the sip stubs needs to be added to the Dockerfile still

**Comment by altendky** [comment]
@BryceBeagle is it documented how to build them, or does that need figured out as well?  I'm just starting to look around a bit.

**Comment by altendky** [comment]
@stlehmann, it looks like you have committed all the updates to `sip.pyi`.  I would have thought it would have come from `PyQt5-sip` but I haven't figured out any way to get it from there.  Perhaps I'm looking in the wrong place?  Once I figure out how to get or make it I'll certainly add it to the `Dockerfile`.

**Comment by altendky** [comment]
Nevermind, looks like it's in SIP proper and included in any install.

**Comment by altendky** [comment]
Do you all get emails when I remove the draft mark?  I'm not sure if I need to ping with a comment like this as well to generate a notification.

**Comment by BryceBeagle** [comment]
I turned off all email notifications, but I don't know if I got an in-Github notification for that specific event either. The notification log just shows that _something_ happnened in a PR, but not _what_.

**Review by BryceBeagle — APPROVED** [review]

**Pull request merged**
