### PR TITLE
Add to QObject.findChild Optional Type and Better Overall Typing

### LINKED ISSUE #10: QObject.findChild should return Optional[QObject]
https://github.com/stlehmann/PyQt5-stubs/blob/189a0497d08ddd65f46e4819f427eb2d03196589/PyQt5-stubs/QtCore.pyi#L1700

QObject.findChild can return a nullpointer, so it gets converted to None in Python.
This means the return value should change from QObject to Optional[QObject]

### PR DESCRIPTION
**Pull request by sweethuman**
Fixes #10 and Specific Return Typing

### CODE REVIEW

**Comment by Djedouas** [comment]
Hi @sweethuman, and thanks for the enhancement :)

However, I have this mypy error on the following example:

`btnAjout = form.dialog.findChild(QPushButton, "btn_ajouterattr")`
`Mypy: Value of type variable "QObjectType" of "findChild" of "QObject" cannot be "QPushButton"`

Any idea?

**Comment by stlehmann** [comment]
@sweethuman Any progress with this PR?

**Comment by stlehmann** [comment]
I'll close this for now as there doesn't seem to be any progress. Feel free to coment if you wish to hang on.

**Comment by sweethuman** [comment]
I'm so sorry, been really busy, I'll get back on it soon.

**Comment by Djedouas** [comment]
Hi @sweethuman 
Any idea for my problem?
Thanks

> Hi @sweethuman, and thanks for the enhancement :)
> 
> However, I have this mypy error on the following example:
> 
> `btnAjout = form.dialog.findChild(QPushButton, "btn_ajouterattr")`
> `Mypy: Value of type variable "QObjectType" of "findChild" of "QObject" cannot be "QPushButton"`
> 
> Any idea?

**Pull request closed without merging**
