### PR TITLE
Fixes annotation for QLineEdit to allow None as argument.

### PR DESCRIPTION
**Pull request by altendky**

### CODE REVIEW

**Comment by bluebird75** [comment]
Try creating a QApplication with the follwing argv : `-platform minimal `

This should run on a gui-less environement.

**Comment by The-Compiler** [comment]
Whoops, that was unintended!

**Comment by altendky** [comment]
I would rather stick with using a full platform plugin and letting pytest-xvfb help out on Linux.

**Review by bluebird75 — APPROVED** [review]
Good for me if it works on all platforms of the CI, let's go this way.

**Comment by altendky** [comment]
@bluebird75, you're tracking the changes more closely than I am.  Go ahead and merge this when it fits.

**Pull request merged**
